apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: debug-allow-all-ingress
  namespace: observability
spec:
  # Select all pods in the namespace
  podSelector: {}
  policyTypes:
  - Ingress
  # Allow ingress traffic from ALL sources
  ingress:
  - {}
